# config/packages/nelmio_cors.yaml
nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: [ '*' ]
    allow_headers: [ '*' ]
    allow_methods: [ '*' ]
    max_age: 3600
  paths:
    '^/api/': ~
